export const content = {
  en: {
    title: "This is multi language app",
    description:
      "Generating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. The writer has no idea what topic the random paragraph will be about when it appears. This forces the writer to use creativity to complete one of three common writing challenges. The writer can use the paragraph as the first one of a short story and build upon it. A second option is to use the random paragraph somewhere in a short story they create. The third option is to have the random paragraph be the ending paragraph in a short story. No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing.Generating random paragraphs can be an excellent way for writers to get their creative flow going at the beginning of the day. The writer has no idea what topic the random paragraph will be about when it appears. This forces the writer to use creativity to complete one of three common writing challenges. The writer can use the paragraph as the first one of a short story and build upon it. A second option is to use the random paragraph somewhere in a short story they create. The third option is to have the random paragraph be the ending paragraph in a short story. No matter which of these challenges is undertaken, the writer is forced to use creativity to incorporate the paragraph into their writing.",
  },
  es: {
    title: "Esta es una aplicación multilingüe",
    description:
      "Generar párrafos aleatorios puede ser una excelente manera para que los escritores inicien su flujo creativo al comienzo del día. El escritor no tiene idea de qué tema tratará el párrafo aleatorio cuando aparezca. Esto obliga al escritor a utilizar la creatividad para completar uno de los tres desafíos de escritura comunes. El escritor puede utilizar el párrafo como el primero de un cuento y desarrollarlo a partir de él. Una segunda opción es utilizar el párrafo aleatorio en algún lugar de una historia corta que creen. La tercera opción es que el párrafo aleatorio sea el párrafo final de un cuento. No importa cuál de estos desafíos se afronte, el escritor se ve obligado a utilizar la creatividad para incorporar el párrafo en su escritura. Generar párrafos aleatorios puede ser una excelente manera para que los escritores inicien su flujo creativo al comienzo del día. El escritor no tiene idea de qué tema tratará el párrafo aleatorio cuando aparezca. Esto obliga al escritor a utilizar la creatividad para completar uno de los tres desafíos de escritura comunes. El escritor puede utilizar el párrafo como el primero de un cuento y desarrollarlo a partir de él. Una segunda opción es utilizar el párrafo aleatorio en algún lugar de una historia corta que creen. La tercera opción es que el párrafo aleatorio sea el párrafo final de un cuento. No importa cuál de estos desafíos se afronte, el escritor se ve obligado a utilizar la creatividad para incorporar el párrafo en su escritura.",
  },
};
